### PR TITLE
Keep toast without notification permission.

### PR DESCRIPTION
**Pull request by ryuunoakaihitomi**
I want to hide background listener service notification, but the toasts of the clipped contents are not shown.

[This is the solution.](https://github.com/ryuunoakaihitomi/ReToast/)

### CODE REVIEW

**Comment by DeweyReed** [comment]
So this is about toasting when the user disables the app notification?

**Comment by ryuunoakaihitomi** [comment]
Yes.

**Comment by DeweyReed** [comment]
Since the library includes some hacks, I'll check them and reply to you later.

BTW, the library could use [App Startup](https://developer.android.com/topic/libraries/app-startup) instead of a custom ContentProvider to provide better performance.

**Comment by ryuunoakaihitomi** [comment]
Thanks for your kind suggestion, but I prefer to use  platform API in order to reduce the cost of importing this library.

**Comment by DeweyReed** [comment]
I found a bug of the library.

```
fun Context.toast(s: String) = Toast.makeText(this, s, Toast.LENGTH_SHORT).show()

toast("a").cancel()
toast("b")
```

On pre-Q devices, without the library, `b` is shown immediately. After adding the library, there is a delay before the toast is shown.

**Comment by ryuunoakaihitomi** [comment]
Good job! Thanks for your bug report! I will fix it in the latest version.

**Comment by ryuunoakaihitomi** [comment]
I have upgraded the library (to version 1.3.0) and fixed the bug.

**Comment by DeweyReed** [comment]
After some reconsideration, I don't think it's good to use such hacks because they could potentially break the app on some devices.

I'm closing the PR. Feel free to fork the repo and build your version of the app.
Thanks for your contribution!

**Pull request closed without merging**
